# Generated by Django 5.0.7 on 2024-07-30 09:40

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('document_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('creation_date', models.DateField(default=django.utils.timezone.now)),
                ('document', models.CharField(max_length=255)),
                ('language', models.CharField(max_length=255)),
                ('version', models.CharField(max_length=255)),
                ('doc_type', models.CharField(max_length=255)),
                ('file_format', models.CharField(max_length=255)),
                ('comments', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ComparisonResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comparison_status', models.CharField(max_length=255)),
                ('similarity_score', models.FloatField()),
                ('summary', models.TextField()),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compareapp.document')),
            ],
        ),
    ]
