# Generated by Django 5.0.7 on 2024-08-28 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compareapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comparisonreport',
            name='comparison_between',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='document',
            name='comparison_between',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
