# Generated by Django 5.0.7 on 2024-07-30 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compareapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='document',
            new_name='doc_format',
        ),
        migrations.RenameField(
            model_name='document',
            old_name='file_format',
            new_name='document_path',
        ),
    ]
