# Generated by Django 5.0.7 on 2024-09-20 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compareapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='author',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='document',
            name='comments',
            field=models.CharField(max_length=255),
        ),
    ]
