# Generated by Django 5.0.7 on 2024-08-12 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compareapp', '0002_alter_comparisonreport_comparison_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comparisonreport',
            name='documents',
        ),
        migrations.RemoveField(
            model_name='comparisonreport',
            name='id',
        ),
        migrations.AlterField(
            model_name='comparisonreport',
            name='report_number',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='document',
            name='new',
            field=models.BooleanField(default=True),
        ),
        migrations.DeleteModel(
            name='DocumentComparison',
        ),
    ]
