# Generated by Django 5.0.7 on 2024-07-30 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compareapp', '0002_rename_document_document_doc_format_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document_path',
            field=models.FileField(upload_to='documents/'),
        ),
    ]
