# Generated by Django 5.0.7 on 2024-09-23 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compareapp', '0003_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='comparisonreport',
            name='ai_summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='ai_summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
