# Generated by Django 5.0.7 on 2024-07-30 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compareapp', '0003_alter_document_document_path'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='document_path',
            new_name='upload_document',
        ),
    ]
