# Generated by Django 5.0.7 on 2024-09-24 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compareapp', '0005_comparisonreport_department_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comparisonreport',
            name='upload_files',
        ),
        migrations.RemoveField(
            model_name='document',
            name='author',
        ),
        migrations.RemoveField(
            model_name='document',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='document',
            name='language',
        ),
        migrations.RemoveField(
            model_name='document',
            name='title',
        ),
        migrations.RemoveField(
            model_name='document',
            name='version',
        ),
    ]
