# Generated by Django 5.0.7 on 2024-09-24 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compareapp', '0007_rename_upload_document_document_upload_documents_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comparisonreport',
            name='comparison_reason',
        ),
    ]
