# Generated by Django 5.0.7 on 2024-09-24 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compareapp', '0008_remove_comparisonreport_comparison_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comparisonreport',
            name='compared_documents',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
