# Generated by Django 5.0.7 on 2024-09-24 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compareapp', '0009_alter_comparisonreport_compared_documents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comparisonreport',
            name='compared_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='comparisonreport',
            name='comparison_summary',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='comparisonreport',
            name='report_path',
            field=models.TextField(blank=True, null=True),
        ),
    ]
