# Generated by Django 5.0.7 on 2024-09-24 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compareapp', '0010_alter_comparisonreport_compared_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comparisonreport',
            name='comparison_between',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
