# Generated by Django 5.0.7 on 2024-10-04 04:39

import compareapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compareapp', '0012_alter_userprofile_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='upload_documents',
            field=models.FileField(default='user_images/user.png', upload_to=compareapp.models.Document.upload_to_path),
        ),
    ]
