# Generated by Django 5.0.7 on 2024-10-05 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compareapp', '0015_userlogs'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlogs',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
