# Generated by Django 5.0.7 on 2024-10-05 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compareapp', '0016_userlogs_last_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userlogs',
            name='user',
        ),
        migrations.AddField(
            model_name='userlogs',
            name='done_by',
            field=models.CharField(default='Unknown', max_length=255),
            preserve_default=False,
        ),
    ]
